#include "rss_ddc.h"

#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

enum { RSS_DDC_PROFILE_SCHEMA_VERSION = 1, RSS_DDC_PROFILE_PATH_MAX = 1024 };
typedef struct { char id[RSS_DDC_PROFILE_ID_MAX]; RSSDDCProfileIdentity identity; RSSDDCProfileSource source;
                 RSSDDCProfileConfidence confidence; size_t control_count;
                 RSSDDCProfileControl controls[RSS_DDC_PROFILE_MAX_CONTROLS]; } ProfileRecord;
struct RSSDDCProfileStore { RSSDDCProfilePackInfo info; bool has_info; size_t profile_count;
                            ProfileRecord profiles[RSS_DDC_PROFILE_MAX_PROFILES]; };
typedef struct { const char *p, *end; } Cursor;

static void ws(Cursor *c) { while (c->p < c->end && isspace((unsigned char)*c->p)) ++c->p; }
static bool take(Cursor *c, char x) { ws(c); if (c->p == c->end || *c->p != x) return false; ++c->p; return true; }
static bool string(Cursor *c, char *out, size_t cap) { size_t n = 0; if (!out || !cap || !take(c, '"')) return false;
    while (c->p < c->end) { unsigned char x = (unsigned char)*c->p++; if (x == '"') { out[n] = 0; return true; }
        if (x < 0x20 || x == '\\' || n + 1 >= cap) return false; out[n++] = (char)x; } return false; }
static bool number(Cursor *c, uint32_t *out) { uint64_t v = 0; ws(c); if (c->p == c->end || !isdigit((unsigned char)*c->p)) return false;
    do { v = v * 10u + (uint32_t)(*c->p++ - '0'); if (v > UINT32_MAX) return false; } while (c->p < c->end && isdigit((unsigned char)*c->p));
    if (c->p < c->end && strchr(".eE", *c->p)) return false; *out = (uint32_t)v; return true; }
static bool boolean(Cursor *c, bool *out) { ws(c); if ((size_t)(c->end-c->p)>=4 && !memcmp(c->p,"true",4)) { c->p+=4; *out=true; return true; }
    if ((size_t)(c->end-c->p)>=5 && !memcmp(c->p,"false",5)) { c->p+=5; *out=false; return true; } return false; }
static bool skip(Cursor *c) { ws(c); if (c->p == c->end) return false; if (*c->p == '"') { char tmp[2]; return string(c,tmp,sizeof(tmp)); }
    if (*c->p == '{' || *c->p == '[') { char open=*c->p++, close=open=='{'?'}':']'; ws(c); if(c->p<c->end&&*c->p==close){++c->p;return true;} for (;;) { if(open=='{' && (!skip(c)||!take(c,':'))) return false; if(!skip(c))return false; ws(c);if(c->p<c->end&&*c->p==close){++c->p;return true;}if(!take(c,','))return false; } }
    if (!strncmp(c->p,"true",4)) { c->p+=4; return true; } if(!strncmp(c->p,"false",5)){c->p+=5;return true;} if(!strncmp(c->p,"null",4)){c->p+=4;return true;}
    uint32_t ignored; return number(c,&ignored); }
static RSSDDCProfileConfidence confidence(const char *s) { static const char *n[]={"unknown","candidate","observed","correlated","set-observed","hardware-validated"}; for(size_t i=1;i<6;i++)if(!strcmp(s,n[i]))return (RSSDDCProfileConfidence)i;return RSS_DDC_PROFILE_CONFIDENCE_UNKNOWN; }
static RSSDDCProfileControlID control(const char *s) { static const char *n[]={"","picture-mode","input","brightness","contrast","color-preset","response-time","adaptive-sync","energy-saving","black-stabilizer","gamma","sharpness","audio-mute"};for(size_t i=1;i<13;i++)if(!strcmp(s,n[i]))return (RSSDDCProfileControlID)i;return RSS_DDC_PROFILE_CONTROL_UNKNOWN; }
static RSSDDCProfileMethod method(const char *s) { return !strcmp(s,"vcp")?RSS_DDC_PROFILE_METHOD_VCP:!strcmp(s,"lg-alt-input")?RSS_DDC_PROFILE_METHOD_LG_ALT_INPUT:RSS_DDC_PROFILE_METHOD_UNKNOWN; }
const char *rss_ddc_profile_control_name(RSSDDCProfileControlID x) { static const char *n[]={"unknown","picture-mode","input","brightness","contrast","color-preset","response-time","adaptive-sync","energy-saving","black-stabilizer","gamma","sharpness","audio-mute"};return (size_t)x<13?n[x]:n[0]; }
const char *rss_ddc_profile_source_name(RSSDDCProfileSource x) { static const char *n[]={"builtin","validated-pack","local","research"};return (size_t)x<4?n[x]:"unknown"; }
const char *rss_ddc_profile_confidence_name(RSSDDCProfileConfidence x) { static const char *n[]={"unknown","candidate","observed","correlated","set-observed","hardware-validated"};return (size_t)x<6?n[x]:n[0]; }

static RSSDDCError identity(Cursor *c, RSSDDCProfileIdentity *id) { bool product=false, provider=false, transport=false, external=false; if(!take(c,'{'))return RSS_DDC_ERROR_PROFILE_MALFORMED; for(;;){char k[48]={};if(!string(c,k,sizeof(k))||!take(c,':'))return RSS_DDC_ERROR_PROFILE_MALFORMED;
    if(!strcmp(k,"manufacturer")){if(id->manufacturer[0]||!string(c,id->manufacturer,sizeof(id->manufacturer)))return RSS_DDC_ERROR_PROFILE_MALFORMED;} else if(!strcmp(k,"productName")){if(product||!string(c,id->product_name,sizeof(id->product_name)))return RSS_DDC_ERROR_PROFILE_MALFORMED;product=true;} else if(!strcmp(k,"serial")){if(id->serial[0]||!string(c,id->serial,sizeof(id->serial)))return RSS_DDC_ERROR_PROFILE_MALFORMED;} else if(!strcmp(k,"branchDeviceId")){if(id->branch_device_id[0]||!string(c,id->branch_device_id,sizeof(id->branch_device_id)))return RSS_DDC_ERROR_PROFILE_MALFORMED;} else if(!strcmp(k,"provider")){char s[RSS_DDC_TEXT_MAX]={};if(provider||!string(c,s,sizeof(s))||(id->provider=rss_ddc_provider_from_registry_class(s))==RSS_DDC_PROVIDER_UNKNOWN)return RSS_DDC_ERROR_PROFILE_MALFORMED;provider=true;} else if(!strcmp(k,"transport")){if(transport||!string(c,id->transport,sizeof(id->transport)))return RSS_DDC_ERROR_PROFILE_MALFORMED;transport=true;} else if(!strcmp(k,"external")){if(external||!boolean(c,&id->external))return RSS_DDC_ERROR_PROFILE_MALFORMED;external=true;} else if(!skip(c))return RSS_DDC_ERROR_PROFILE_MALFORMED; ws(c);if(c->p<c->end&&*c->p=='}'){++c->p;break;}if(!take(c,','))return RSS_DDC_ERROR_PROFILE_MALFORMED;} return product&&provider&&transport&&external&&id->product_name[0]&&id->transport[0]?RSS_DDC_OK:RSS_DDC_ERROR_PROFILE_MALFORMED; }
static RSSDDCError enums(Cursor *c,RSSDDCProfileControl *q){if(!take(c,'['))return RSS_DDC_ERROR_PROFILE_MALFORMED;ws(c);if(c->p<c->end&&*c->p==']'){++c->p;return RSS_DDC_OK;}for(;;){RSSDDCProfileEnumValue v={};bool a=false,b=false,d=false;if(q->enum_value_count==RSS_DDC_PROFILE_MAX_ENUM_VALUES||!take(c,'{'))return RSS_DDC_ERROR_PROFILE_MALFORMED;for(;;){char k[32]={};if(!string(c,k,sizeof(k))||!take(c,':'))return RSS_DDC_ERROR_PROFILE_MALFORMED;if(!strcmp(k,"id")){if(a||!string(c,v.id,sizeof(v.id)))return RSS_DDC_ERROR_PROFILE_MALFORMED;a=true;}else if(!strcmp(k,"name")){if(b||!string(c,v.name,sizeof(v.name)))return RSS_DDC_ERROR_PROFILE_MALFORMED;b=true;}else if(!strcmp(k,"value")){uint32_t x;if(d||!number(c,&x)||x>UINT16_MAX)return RSS_DDC_ERROR_PROFILE_MALFORMED;v.raw_value=(uint16_t)x;d=true;}else if(!skip(c))return RSS_DDC_ERROR_PROFILE_MALFORMED;ws(c);if(c->p<c->end&&*c->p=='}'){++c->p;break;}if(!take(c,','))return RSS_DDC_ERROR_PROFILE_MALFORMED;}if(!a||!b||!d||!v.id[0])return RSS_DDC_ERROR_PROFILE_MALFORMED;for(size_t i=0;i<q->enum_value_count;i++)if(!strcmp(v.id,q->enum_values[i].id)||v.raw_value==q->enum_values[i].raw_value)return RSS_DDC_ERROR_PROFILE_CONFLICT;q->enum_values[q->enum_value_count++]=v;ws(c);if(c->p<c->end&&*c->p==']'){++c->p;return RSS_DDC_OK;}if(!take(c,','))return RSS_DDC_ERROR_PROFILE_MALFORMED;}}
static RSSDDCError one_control(Cursor *c,RSSDDCProfileControl *q,RSSDDCProfileSource source){bool a=false,b=false,d=false,e=false,f=false,g=false,h=false;if(!take(c,'{'))return RSS_DDC_ERROR_PROFILE_MALFORMED;for(;;){char k[32]={},s[64]={};if(!string(c,k,sizeof(k))||!take(c,':'))return RSS_DDC_ERROR_PROFILE_MALFORMED;if(!strcmp(k,"id")){if(a||!string(c,s,sizeof(s))||(q->id=control(s))==RSS_DDC_PROFILE_CONTROL_UNKNOWN)return RSS_DDC_ERROR_PROFILE_MALFORMED;a=true;}else if(!strcmp(k,"method")){if(b||!string(c,s,sizeof(s))||(q->method=method(s))==RSS_DDC_PROFILE_METHOD_UNKNOWN)return RSS_DDC_ERROR_PROFILE_MALFORMED;b=true;}else if(!strcmp(k,"address")){uint32_t x;if(d||!number(c,&x)||x>UINT16_MAX)return RSS_DDC_ERROR_PROFILE_MALFORMED;q->address=(uint16_t)x;d=true;}else if(!strcmp(k,"readable")){if(e||!boolean(c,&q->readable))return RSS_DDC_ERROR_PROFILE_MALFORMED;e=true;}else if(!strcmp(k,"writable")){if(f||!boolean(c,&q->writable))return RSS_DDC_ERROR_PROFILE_MALFORMED;f=true;}else if(!strcmp(k,"confidence")){if(g||!string(c,s,sizeof(s))||(q->confidence=confidence(s))==RSS_DDC_PROFILE_CONFIDENCE_UNKNOWN)return RSS_DDC_ERROR_PROFILE_MALFORMED;g=true;}else if(!strcmp(k,"enums")){if(h)return RSS_DDC_ERROR_PROFILE_MALFORMED;RSSDDCError z=enums(c,q);if(z)return z;h=true;}else if(!skip(c))return RSS_DDC_ERROR_PROFILE_MALFORMED;ws(c);if(c->p<c->end&&*c->p=='}'){++c->p;break;}if(!take(c,','))return RSS_DDC_ERROR_PROFILE_MALFORMED;}if(!a||!b||!d||!e||!f||!g||!h||!q->address)return RSS_DDC_ERROR_PROFILE_MALFORMED;if(q->method==RSS_DDC_PROFILE_METHOD_VCP&&q->address>UINT8_MAX)return RSS_DDC_ERROR_PROFILE_MALFORMED;if(q->method==RSS_DDC_PROFILE_METHOD_LG_ALT_INPUT&&q->id!=RSS_DDC_PROFILE_CONTROL_INPUT)return RSS_DDC_ERROR_PROFILE_UNSAFE;if(q->id==RSS_DDC_PROFILE_CONTROL_INPUT&&q->method==RSS_DDC_PROFILE_METHOD_VCP&&q->address!=0x60)return RSS_DDC_ERROR_PROFILE_UNSAFE;if(q->id==RSS_DDC_PROFILE_CONTROL_PICTURE_MODE&&!q->enum_value_count)return RSS_DDC_ERROR_PROFILE_MALFORMED;if(q->writable&&(source==RSS_DDC_PROFILE_SOURCE_RESEARCH||q->confidence!=RSS_DDC_PROFILE_CONFIDENCE_HARDWARE_VALIDATED))return RSS_DDC_ERROR_PROFILE_UNSAFE;return RSS_DDC_OK;}

static bool equal_id(const RSSDDCProfileIdentity *a,const RSSDDCProfileIdentity *b){return a->provider==b->provider&&a->external==b->external&&!strcmp(a->manufacturer,b->manufacturer)&&!strcmp(a->product_name,b->product_name)&&!strcmp(a->serial,b->serial)&&!strcmp(a->branch_device_id,b->branch_device_id)&&!strcmp(a->transport,b->transport);}
static RSSDDCError profile(Cursor *c,ProfileRecord *r,RSSDDCProfileSource source){bool a=false,b=false,d=false,e=false;r->source=source;if(!take(c,'{'))return RSS_DDC_ERROR_PROFILE_MALFORMED;for(;;){char k[32]={},s[64]={};if(!string(c,k,sizeof(k))||!take(c,':'))return RSS_DDC_ERROR_PROFILE_MALFORMED;if(!strcmp(k,"id")){if(a||!string(c,r->id,sizeof(r->id)))return RSS_DDC_ERROR_PROFILE_MALFORMED;a=true;}else if(!strcmp(k,"identity")){if(b)return RSS_DDC_ERROR_PROFILE_MALFORMED;RSSDDCError z=identity(c,&r->identity);if(z)return z;b=true;}else if(!strcmp(k,"confidence")){if(d||!string(c,s,sizeof(s))||(r->confidence=confidence(s))==RSS_DDC_PROFILE_CONFIDENCE_UNKNOWN)return RSS_DDC_ERROR_PROFILE_MALFORMED;d=true;}else if(!strcmp(k,"controls")){if(e||!take(c,'['))return RSS_DDC_ERROR_PROFILE_MALFORMED;ws(c);if(c->p<c->end&&*c->p==']')return RSS_DDC_ERROR_PROFILE_MALFORMED;for(;;){if(r->control_count==RSS_DDC_PROFILE_MAX_CONTROLS)return RSS_DDC_ERROR_PROFILE_MALFORMED;RSSDDCError z=one_control(c,&r->controls[r->control_count],source);if(z)return z;if((unsigned)r->controls[r->control_count].confidence>(unsigned)r->confidence)return RSS_DDC_ERROR_PROFILE_MALFORMED;for(size_t i=0;i<r->control_count;i++)if(r->controls[i].id==r->controls[r->control_count].id)return RSS_DDC_ERROR_PROFILE_CONFLICT;++r->control_count;ws(c);if(c->p<c->end&&*c->p==']'){++c->p;break;}if(!take(c,','))return RSS_DDC_ERROR_PROFILE_MALFORMED;}e=true;}else if(!skip(c))return RSS_DDC_ERROR_PROFILE_MALFORMED;ws(c);if(c->p<c->end&&*c->p=='}'){++c->p;break;}if(!take(c,','))return RSS_DDC_ERROR_PROFILE_MALFORMED;}return a&&b&&d&&e&&r->id[0]?RSS_DDC_OK:RSS_DDC_ERROR_PROFILE_MALFORMED;}
static bool version_ok(const char *s){unsigned a,b,c;char x;return sscanf(s,"%u.%u.%u%c",&a,&b,&c,&x)==3&&a==RSS_DDC_VERSION_MAJOR&&(b<RSS_DDC_VERSION_MINOR||(b==RSS_DDC_VERSION_MINOR&&c<=RSS_DDC_VERSION_PATCH));}
static RSSDDCError parse_pack(const char *data,size_t len,RSSDDCProfileSource source,RSSDDCProfileStore *out){if(!data||!len||len>RSS_DDC_PROFILE_FILE_MAX_BYTES||!out||source==RSS_DDC_PROFILE_SOURCE_BUILTIN)return RSS_DDC_ERROR_ARGUMENT;Cursor c={data,data+len};bool a=false,b=false,d=false,e=false;if(!take(&c,'{'))return RSS_DDC_ERROR_PROFILE_MALFORMED;for(;;){char k[48]={};if(!string(&c,k,sizeof(k))||!take(&c,':'))return RSS_DDC_ERROR_PROFILE_MALFORMED;if(!strcmp(k,"schemaVersion")){uint32_t x;if(a||!number(&c,&x))return RSS_DDC_ERROR_PROFILE_MALFORMED;out->info.schema_version=x;a=true;}else if(!strcmp(k,"databaseVersion")){if(b||!string(&c,out->info.database_version,sizeof(out->info.database_version)))return RSS_DDC_ERROR_PROFILE_MALFORMED;b=true;}else if(!strcmp(k,"minimumRSSDDCVersion")){if(d||!string(&c,out->info.minimum_rss_ddc_version,sizeof(out->info.minimum_rss_ddc_version)))return RSS_DDC_ERROR_PROFILE_MALFORMED;d=true;}else if(!strcmp(k,"packId")){if(out->info.pack_id[0]||!string(&c,out->info.pack_id,sizeof(out->info.pack_id)))return RSS_DDC_ERROR_PROFILE_MALFORMED;}else if(!strcmp(k,"profiles")){if(e||!take(&c,'['))return RSS_DDC_ERROR_PROFILE_MALFORMED;ws(&c);if(c.p<c.end&&*c.p==']')++c.p;else for(;;){if(out->profile_count==RSS_DDC_PROFILE_MAX_PROFILES)return RSS_DDC_ERROR_PROFILE_MALFORMED;RSSDDCError z=profile(&c,&out->profiles[out->profile_count],source);if(z)return z;for(size_t i=0;i<out->profile_count;i++)if(equal_id(&out->profiles[i].identity,&out->profiles[out->profile_count].identity))return RSS_DDC_ERROR_PROFILE_CONFLICT;++out->profile_count;ws(&c);if(c.p<c.end&&*c.p==']'){++c.p;break;}if(!take(&c,','))return RSS_DDC_ERROR_PROFILE_MALFORMED;}e=true;}else if(!skip(&c))return RSS_DDC_ERROR_PROFILE_MALFORMED;ws(&c);if(c.p<c.end&&*c.p=='}'){++c.p;break;}if(!take(&c,','))return RSS_DDC_ERROR_PROFILE_MALFORMED;}ws(&c);if(c.p!=c.end||!a||!b||!d||!e||!out->info.database_version[0]||!out->info.minimum_rss_ddc_version[0])return RSS_DDC_ERROR_PROFILE_MALFORMED;if(out->info.schema_version!=RSS_DDC_PROFILE_SCHEMA_VERSION)return RSS_DDC_ERROR_PROFILE_SCHEMA;if(!version_ok(out->info.minimum_rss_ddc_version))return RSS_DDC_ERROR_PROFILE_VERSION;out->has_info=true;return RSS_DDC_OK;}

RSSDDCProfileStore *rss_ddc_profile_store_create(void){return calloc(1,sizeof(RSSDDCProfileStore));}
void rss_ddc_profile_store_destroy(RSSDDCProfileStore *s){free(s);}
static RSSDDCError add(RSSDDCProfileStore *s,const RSSDDCProfileStore *p){if(!s||!p||s->profile_count+p->profile_count>RSS_DDC_PROFILE_MAX_PROFILES)return RSS_DDC_ERROR_PROFILE_CONFLICT;RSSDDCProfileStore *r=rss_ddc_profile_store_create();if(!r)return RSS_DDC_ERROR_SYSTEM;memcpy(r,s,sizeof(*r));for(size_t i=0;i<p->profile_count;i++)r->profiles[r->profile_count++]=p->profiles[i];r->info=p->info;r->has_info=true;memcpy(s,r,sizeof(*s));rss_ddc_profile_store_destroy(r);return RSS_DDC_OK;}
static RSSDDCError load(RSSDDCProfileStore *s,const char *d,size_t n,RSSDDCProfileSource source){if(!s)return RSS_DDC_ERROR_ARGUMENT;RSSDDCProfileStore *p=rss_ddc_profile_store_create();if(!p)return RSS_DDC_ERROR_SYSTEM;RSSDDCError z=parse_pack(d,n,source,p);if(!z)z=add(s,p);rss_ddc_profile_store_destroy(p);return z;}
RSSDDCError rss_ddc_profile_store_load_pack_data(RSSDDCProfileStore*s,const char*d,size_t n){return load(s,d,n,RSS_DDC_PROFILE_SOURCE_VALIDATED_PACK);} RSSDDCError rss_ddc_profile_store_load_local_data(RSSDDCProfileStore*s,const char*d,size_t n){return load(s,d,n,RSS_DDC_PROFILE_SOURCE_LOCAL);} RSSDDCError rss_ddc_profile_store_load_research_data(RSSDDCProfileStore*s,const char*d,size_t n){return load(s,d,n,RSS_DDC_PROFILE_SOURCE_RESEARCH);} RSSDDCError rss_ddc_profile_validate_pack_data(const char*d,size_t n,RSSDDCProfileSource x,RSSDDCProfilePackInfo*i){RSSDDCProfileStore*p=rss_ddc_profile_store_create();if(!p)return RSS_DDC_ERROR_SYSTEM;RSSDDCError z=parse_pack(d,n,x,p);if(!z&&i)*i=p->info;rss_ddc_profile_store_destroy(p);return z;}

static RSSDDCError load_file(RSSDDCProfileStore*s,const char *path,RSSDDCProfileSource source){if(!s||!path)return RSS_DDC_ERROR_ARGUMENT;FILE*f=fopen(path,"rb");if(!f)return RSS_DDC_ERROR_READ;char *d=calloc(1,RSS_DDC_PROFILE_FILE_MAX_BYTES+1);if(!d){fclose(f);return RSS_DDC_ERROR_SYSTEM;}size_t n=fread(d,1,RSS_DDC_PROFILE_FILE_MAX_BYTES,f);int failed=ferror(f);int extra=EOF;if(!failed&&n==RSS_DDC_PROFILE_FILE_MAX_BYTES)extra=fgetc(f);fclose(f);RSSDDCError z=(failed||extra!=EOF)?RSS_DDC_ERROR_PROFILE_MALFORMED:load(s,d,n,source);free(d);return z;}
RSSDDCError rss_ddc_profile_store_load_pack_file(RSSDDCProfileStore*s,const char*p){return load_file(s,p,RSS_DDC_PROFILE_SOURCE_VALIDATED_PACK);} RSSDDCError rss_ddc_profile_store_load_local_file(RSSDDCProfileStore*s,const char*p){return load_file(s,p,RSS_DDC_PROFILE_SOURCE_LOCAL);} RSSDDCError rss_ddc_profile_store_load_research_file(RSSDDCProfileStore*s,const char*p){return load_file(s,p,RSS_DDC_PROFILE_SOURCE_RESEARCH);} RSSDDCError rss_ddc_profile_store_pack_info(const RSSDDCProfileStore*s,RSSDDCProfilePackInfo*i){if(!s||!i)return RSS_DDC_ERROR_ARGUMENT;if(!s->has_info)return RSS_DDC_ERROR_NOT_FOUND;*i=s->info;return RSS_DDC_OK;}

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-nonliteral"
static void emit(char*b,size_t cap,size_t *n,const char *fmt,...){va_list a;va_start(a,fmt);int w=vsnprintf(b&&*n<cap?b+*n:NULL,b&&*n<cap?cap-*n:0,fmt,a);va_end(a);if(w>0)*n+=(size_t)w;}
#pragma clang diagnostic pop
RSSDDCError rss_ddc_profile_store_export_json(const RSSDDCProfileStore*s,char*b,size_t cap,size_t*required){if(!s||!required)return RSS_DDC_ERROR_ARGUMENT;size_t n=0;emit(b,cap,&n,"{\"schemaVersion\":1,\"databaseVersion\":\"%s\",\"minimumRSSDDCVersion\":\"%s\",\"packId\":\"%s\",\"profiles\":[",s->has_info?s->info.database_version:"local-export",s->has_info?s->info.minimum_rss_ddc_version:"0.1.0",s->has_info?s->info.pack_id:"local-export");for(size_t i=0;i<s->profile_count;i++){const ProfileRecord*r=&s->profiles[i];emit(b,cap,&n,"%s{\"id\":\"%s\",\"identity\":{\"productName\":\"%s\",\"provider\":\"%s\",\"transport\":\"%s\",\"external\":%s",i?",":"",r->id,r->identity.product_name,rss_ddc_provider_string(r->identity.provider),r->identity.transport,r->identity.external?"true":"false");if(r->identity.manufacturer[0])emit(b,cap,&n,",\"manufacturer\":\"%s\"",r->identity.manufacturer);if(r->identity.serial[0])emit(b,cap,&n,",\"serial\":\"%s\"",r->identity.serial);if(r->identity.branch_device_id[0])emit(b,cap,&n,",\"branchDeviceId\":\"%s\"",r->identity.branch_device_id);emit(b,cap,&n,"},\"confidence\":\"%s\",\"controls\":[",rss_ddc_profile_confidence_name(r->confidence));for(size_t j=0;j<r->control_count;j++){const RSSDDCProfileControl*q=&r->controls[j];emit(b,cap,&n,"%s{\"id\":\"%s\",\"method\":\"%s\",\"address\":%u,\"readable\":%s,\"writable\":%s,\"confidence\":\"%s\",\"enums\":[",j?",":"",rss_ddc_profile_control_name(q->id),q->method==RSS_DDC_PROFILE_METHOD_VCP?"vcp":"lg-alt-input",q->address,q->readable?"true":"false",q->writable?"true":"false",rss_ddc_profile_confidence_name(q->confidence));for(size_t k=0;k<q->enum_value_count;k++)emit(b,cap,&n,"%s{\"id\":\"%s\",\"name\":\"%s\",\"value\":%u}",k?",":"",q->enum_values[k].id,q->enum_values[k].name,q->enum_values[k].raw_value);emit(b,cap,&n,"]}");}emit(b,cap,&n,"]}");}emit(b,cap,&n,"]}");*required=n+1;if(!b&&!cap)return RSS_DDC_OK;if(!b||cap<n+1)return RSS_DDC_ERROR_ARGUMENT;b[n]=0;return RSS_DDC_OK;}
RSSDDCError rss_ddc_profile_store_save_file(const RSSDDCProfileStore*s,const char*path){if(!s||!path||strlen(path)>RSS_DDC_PROFILE_PATH_MAX)return RSS_DDC_ERROR_ARGUMENT;size_t n=0;RSSDDCError z=rss_ddc_profile_store_export_json(s,NULL,0,&n);if(z)return z;char *d=malloc(n),*tmp=malloc(strlen(path)+12);if(!d||!tmp){free(d);free(tmp);return RSS_DDC_ERROR_SYSTEM;}z=rss_ddc_profile_store_export_json(s,d,n,&n);if(z){free(d);free(tmp);return z;}snprintf(tmp,strlen(path)+12,"%s.tmp.XXXXXX",path);int fd=mkstemp(tmp);if(fd<0){free(d);free(tmp);return RSS_DDC_ERROR_SYSTEM;}size_t off=0;while(off<n-1){ssize_t w=write(fd,d+off,n-1-off);if(w<=0){z=RSS_DDC_ERROR_SYSTEM;break;}off+=(size_t)w;}if(!z&&fsync(fd)!=0)z=RSS_DDC_ERROR_SYSTEM;if(close(fd)!=0&&!z)z=RSS_DDC_ERROR_SYSTEM;if(!z&&rename(tmp,path)!=0)z=RSS_DDC_ERROR_SYSTEM;if(z)unlink(tmp);free(d);free(tmp);return z;}

static bool match(const RSSDDCProfileIdentity *p, const RSSDDCProfileIdentity *a, unsigned *score) {
    if (p->provider != a->provider || p->external != a->external || strcmp(p->product_name, a->product_name) ||
        strcmp(p->transport, a->transport)) return false;
    unsigned n = 4;
    if (p->manufacturer[0]) { if (strcmp(p->manufacturer, a->manufacturer)) return false; ++n; }
    if (p->serial[0]) { if (strcmp(p->serial, a->serial)) return false; ++n; }
    if (p->branch_device_id[0]) { if (strcmp(p->branch_device_id, a->branch_device_id)) return false; ++n; }
    *score = n;
    return true;
}
static unsigned rank(RSSDDCProfileSource x){static const unsigned r[]={2,3,4,1};return (size_t)x<4?r[x]:0;}
static bool equal_control(const RSSDDCProfileControl*a,const RSSDDCProfileControl*b){return a->method==b->method&&a->address==b->address&&a->readable==b->readable&&a->writable==b->writable&&a->enum_value_count==b->enum_value_count&&!memcmp(a->enum_values,b->enum_values,a->enum_value_count*sizeof(a->enum_values[0]));}
RSSDDCError rss_ddc_profile_store_resolve(const RSSDDCProfileStore*s,const RSSDDCProfileIdentity*id,RSSDDCEffectiveProfile*out){if(!s||!id||!out)return RSS_DDC_ERROR_ARGUMENT;RSSDDCEffectiveProfile*r=calloc(1,sizeof(*r));if(!r)return RSS_DDC_ERROR_SYSTEM;r->identity=*id;unsigned co[RSS_DDC_PROFILE_MAX_CONTROLS]={},so[RSS_DDC_PROFILE_MAX_CONTROLS]={},sp[RSS_DDC_PROFILE_MAX_CONTROLS]={};RSSDDCError z=RSS_DDC_OK;for(size_t i=0;i<s->profile_count&&!z;i++){const ProfileRecord*p=&s->profiles[i];unsigned score;if(!match(&p->identity,id,&score))continue;for(size_t j=0;j<p->control_count;j++){const RSSDDCProfileControl*q=&p->controls[j];size_t k=0;while(k<r->control_count&&r->controls[k].id!=q->id)++k;if(k==r->control_count){if(k==RSS_DDC_PROFILE_MAX_CONTROLS){z=RSS_DDC_ERROR_PROFILE_CONFLICT;break;}r->controls[k]=*q;r->controls[k].source=p->source;r->controls[k].write_authorized=q->writable&&q->confidence==RSS_DDC_PROFILE_CONFIDENCE_HARDWARE_VALIDATED&&p->source!=RSS_DDC_PROFILE_SOURCE_RESEARCH;co[k]=q->confidence;so[k]=rank(p->source);sp[k]=score;++r->control_count;continue;}if((unsigned)q->confidence>co[k]||((unsigned)q->confidence==co[k]&&(rank(p->source)>so[k]||(rank(p->source)==so[k]&&score>sp[k])))){r->controls[k]=*q;r->controls[k].source=p->source;r->controls[k].write_authorized=q->writable&&q->confidence==RSS_DDC_PROFILE_CONFIDENCE_HARDWARE_VALIDATED&&p->source!=RSS_DDC_PROFILE_SOURCE_RESEARCH;co[k]=q->confidence;so[k]=rank(p->source);sp[k]=score;}else if((unsigned)q->confidence==co[k]&&rank(p->source)==so[k]&&score==sp[k]&&!equal_control(q,&r->controls[k]))z=RSS_DDC_ERROR_PROFILE_CONFLICT;}}if(!z&&!r->control_count)z=RSS_DDC_ERROR_NOT_FOUND;if(!z)*out=*r;free(r);return z;}
size_t rss_ddc_effective_profile_control_count(const RSSDDCEffectiveProfile*e){return e?e->control_count:0;} RSSDDCError rss_ddc_effective_profile_control(const RSSDDCEffectiveProfile*e,size_t i,RSSDDCProfileControl*c){if(!e||!c)return RSS_DDC_ERROR_ARGUMENT;if(i>=e->control_count)return RSS_DDC_ERROR_NOT_FOUND;*c=e->controls[i];return RSS_DDC_OK;} RSSDDCError rss_ddc_profile_control_enum_value(const RSSDDCProfileControl*c,size_t i,RSSDDCProfileEnumValue*v){if(!c||!v)return RSS_DDC_ERROR_ARGUMENT;if(i>=c->enum_value_count)return RSS_DDC_ERROR_NOT_FOUND;*v=c->enum_values[i];return RSS_DDC_OK;}
void rss_ddc_profile_identity_from_display(const RSSDDCDisplay*d,RSSDDCProfileIdentity*i){if(!i)return;*i=(RSSDDCProfileIdentity){};if(!d)return;snprintf(i->manufacturer,sizeof(i->manufacturer),"%s",d->manufacturer);snprintf(i->product_name,sizeof(i->product_name),"%s",d->product_name);snprintf(i->serial,sizeof(i->serial),"%s",d->serial);snprintf(i->branch_device_id,sizeof(i->branch_device_id),"%s",d->branch_device_id);snprintf(i->transport,sizeof(i->transport),"%s",d->transport);i->provider=d->provider;i->external=d->external;}

static const char builtin[] = "{\"schemaVersion\":1,\"databaseVersion\":\"2026.08.14.2\",\"minimumRSSDDCVersion\":\"0.1.0\",\"packId\":\"rogue-builtin\",\"profiles\":[{\"id\":\"lg-hdr-qhd-dcpdp13-dcpext0\",\"identity\":{\"productName\":\"LG HDR QHD\",\"provider\":\"DCPDP13Service\",\"transport\":\"DCPEXT0\",\"external\":true},\"confidence\":\"hardware-validated\",\"controls\":[{\"id\":\"picture-mode\",\"method\":\"vcp\",\"address\":21,\"readable\":true,\"writable\":true,\"confidence\":\"hardware-validated\",\"enums\":[{\"id\":\"vivid\",\"name\":\"Vivid\",\"value\":49},{\"id\":\"reader\",\"name\":\"Reader\",\"value\":1}]}]}]}";
RSSDDCError rss_ddc_profile_store_load_builtin(RSSDDCProfileStore *s) { if (!s) return RSS_DDC_ERROR_ARGUMENT; RSSDDCProfileStore *p = rss_ddc_profile_store_create(); if (!p) return RSS_DDC_ERROR_SYSTEM; RSSDDCError z = parse_pack(builtin, sizeof(builtin)-1, RSS_DDC_PROFILE_SOURCE_VALIDATED_PACK, p); if (!z) { for (size_t i=0;i<p->profile_count;i++) p->profiles[i].source = RSS_DDC_PROFILE_SOURCE_BUILTIN; z=add(s,p); } rss_ddc_profile_store_destroy(p); return z; }
